import React, { useState } from "react";
import AppLayout from "./AppLayout";
import { useNavigate } from "react-router-dom";
import { useLocation } from "react-router-dom";
import "./ReportDetails.css";

const ReportDetails = () => {
   const [showShareModal, setShowShareModal] =
    useState(false);
    const navigate = useNavigate();
    const location = useLocation();
    const generateReport = () => {
     
};
const exportData = () => {

  const csvData = `
Study,Enrollment,Compliance
TRIA-001,2200,96%
COVID-19,2200,On Track
Diabetes,900,Delayed
`;

  const blob = new Blob(
    [csvData],
    { type: "text/csv" }
  );

  const url =
    window.URL.createObjectURL(blob);

  const a =
    document.createElement("a");

  a.href = url;
  a.download = "StudyReport.csv";
  a.click();
};

const reportType =
  location.state?.reportType || "Study Reports";
  let reportData = [];
  if (reportType === "Study Reports") {
  reportData = [
    { name: "COVID-19", status: "On Track", value: "2200" },
    { name: "Diabetes", status: "Delayed", value: "900" }
  ];
}

else if (reportType === "Enrollment Reports") {
  reportData = [
    { name: "Apollo Site", status: "83%", value: "250" },
    { name: "AIG Site", status: "60%", value: "180" }
  ];
}

else if (reportType === "Compliance Reports") {
  reportData = [
    { name: "eTMF", status: "Completed", value: "98%" },
    { name: "Regulatory", status: "Pending", value: "90%" }
  ];
}

else if (reportType === "Executive Reports") {
  reportData = [
    { name: "Portfolio", status: "24 Studies", value: "18 Active" }
  ];
}

else if (reportType === "Operational Reports") {
  reportData = [
    { name: "Sites", status: "156", value: "142 Active" }
  ];
}

else {
  reportData = [
    { name: "Dashboard Export", status: "Ready", value: "PDF" }
  ];
}
  return (
    <AppLayout>
      <div className="report-details-page">

      <div className="page-header">

 <div className="page-header">
 

  <h1 className="report-title">
  {reportType}
</h1>
</div>

</div>

        <div className="kpi-grid">

          <div className="kpi-card">
            <h3>Total Reports</h3>
            <h2>24</h2>
          </div>

          <div className="kpi-card">
            <h3>Generated Today</h3>
            <h2>8</h2>
          </div>

          <div className="kpi-card">
            <h3>Exports</h3>
            <h2>15</h2>
          </div>

          <div className="kpi-card">
            <h3>Pending</h3>
            <h2>3</h2>
          </div>

        </div>

        <div className="details-card">
  <h2>Report Overview</h2>

  <div className="details-grid">
    <div>
      <strong>Report ID</strong>
      <p>RPT-001</p>
    </div>

    <div>
      <strong>Generated By</strong>
      <p>Sponsor Admin</p>
    </div>

    <div>
      <strong>Generated Date</strong>
      <p>2026-06-01</p>
    </div>

    <div>
      <strong>Status</strong>
      <p>Ready</p>
    </div>
  </div>
</div>

<div className="details-card">
  <h2>Report Analytics</h2>

  <table className="sponsor-table">
    <thead>
      <tr>
        <th>Metric</th>
        <th>Value</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td>Total Sites</td>
        <td>15</td>
      </tr>

      <tr>
        <td>Total Subjects</td>
        <td>3200</td>
      </tr>

      <tr>
        <td>Completed Visits</td>
        <td>91%</td>
      </tr>

      <tr>
        <td>Compliance Score</td>
        <td>96%</td>
      </tr>
    </tbody>
  </table>
</div>

<div className="details-card">
  <h2>Site Performance Summary</h2>

  <table className="sponsor-table">
    <thead>
      <tr>
        <th>Site</th>
        <th>Enrollment</th>
        <th>Compliance</th>
        <th>Status</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td>Apollo Hospital</td>
        <td>420</td>
        <td>98%</td>
        <td>Excellent</td>
      </tr>

      <tr>
        <td>Care Hospital</td>
        <td>310</td>
        <td>95%</td>
        <td>Good</td>
      </tr>
    </tbody>
  </table>
</div>
        <div className="report-table-section">

  <h2>{reportType} Summary</h2>

  <table className="report-table">

    <thead>
      <tr>
        <th>Study</th>
        <th>Status</th>
        <th>Enrollment</th>
      </tr>
    </thead>

   <tbody>

{reportData.map((item, index) => (
  <tr key={index}>
    <td>{item.name}</td>
    <td>{item.status}</td>
    <td>{item.value}</td>
  </tr>
))}

</tbody>

  </table>

</div>

<div className="details-card">
  <h2>Report Actions</h2>

  <div className="action-buttons">

    <button onClick={generateReport}>
      Download PDF
    </button>

    <button onClick={exportData}>
      Export CSV
    </button>

    <button
  onClick={() => setShowShareModal(true)}
>
  Share Report
</button>

    <button onClick={() => navigate(-1)}>
      Back
    </button>

  </div>
</div>
      </div>

      {
  showShareModal && (
    <div className="details-card">

      <h2>Share Report</h2>

      <div className="action-buttons">

        <button>
          Email Report
        </button>

        <button>
          Copy Link
        </button>

        <button>
          Download PDF
        </button>

        <button
          onClick={() =>
            setShowShareModal(false)
          }
        >
          Close
        </button>

      </div>

    </div>
  )
}
    </AppLayout>
  );
};

export default ReportDetails;